[ui]
foreground = "#ffffff"
background = "#0d1117"
cursor = "#ffdd33"
selection = "#ffdd33"

[syntax]
black = "#24292e"
red = "#ff5555"
green = "#44ff44"
yellow = "#ffdd33"
blue = "#4da6ff"
magenta = "#c678dd"
cyan = "#33cccc"
white = "#ffffff"

[syntax_bright]
black = "#50575e"
red = "#ff8888"
green = "#88ff88"
yellow = "#ffee88"
blue = "#80c0ff"
magenta = "#e1aaff"
cyan = "#66ffff"
white = "#ffffff"

