[ui]
foreground = "#c9d1d9"
background = "#161b22"
cursor = "#58a6ff"
selection = "#1f6feb"

[syntax]
black = "#30363d"
red = "#f85149"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[syntax_bright]
black = "#8b949e"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#ffffff"

